/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeMethod_NativeExample */

#ifndef _Included_NativeMethod_NativeExample
#define _Included_NativeMethod_NativeExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeMethod_NativeExample
 * Method:    printMessage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeMethod_NativeExample_printMessage
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
